project:
  type: manuscript
  output-dir: _output

manuscript:
  article: index.qmd

format:
  pdf:
    template: template.tex
    keep-tex: true
    pdf-engine: pdflatex
    cite-method: natbib
    number-sections: true
    shift-heading-level-by: -1
    fig-pos: "tbp"
    tbl-cap-location: top
    filters:
      - _table-filter.lua
    include-in-header:
      - _preamble.tex
  html:
    toc: true
    toc-depth: 3
    number-sections: true
    theme:
      - cosmo
      - styles.scss
    code-fold: true
    html-math-method: katex
    embed-resources: true

bibliography: references.bib
